language: node_js
node_js:
  - lts/*

cache:
  yarn: true
  directories:
    - 'node_modules'

script:
  - yarn run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  allow-empty-commit: true
  local-dir: ./public
  on:
    branch: master
